### ISSUE TITLE
scannable pdf not supported

### ISSUE THREAD

**Issue by codebanesr** [hertzg/tesseract-server#123]
Pdf reading is not supported\nError during processing

[sample scannable pdf.pdf](https://github.com/hertzg/tesseract-server/files/13403922/sample.scannable.pdf.pdf)
i tried uploading the following scannable pdf file, got the error 
```
{
    "data": {
        "exit": {
            "code": 1,
            "signal": null
        },
        "stderr": "Error in pixReadMem: Pdf reading is not supported\nError during processing.\n",
        "stdout": ""
    }
}
```

This should be supported by defaul!

**Comment by hertzg** [comment]
This is out of scope of this project, project provides a way to run tesseract via http, if you want tesseract to support something you can use your pre-built tesseract executable which supports what you want to achieve.
