### ISSUE TITLE
curl not work 

### ISSUE THREAD

**Issue by amitx-code** [hertzg/tesseract-server#56]
i run docker docker -p 8884:8884 hertzg/tesseract-server:latest 
i do curl http://127.0.0.1:8884/status
he say connection reset by peer
waths wrong?

**Comment by DiegoFSFlor** [comment]
is there message in docker log?

**Comment by hertzg** [comment]
Fixed in [v2.5.1](https://github.com/hertzg/tesseract-server/compare/v2.5.0...v2.5.1)
